using System;
using System.Collections.Immutable;
using System.Linq;
using CoreOne.Attributes;
using CoreOne.Generators.Proxies;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Tests.Generators;

public class ProxyGeneratorTests
{
    // Shared interceptor boilerplate injected into every test source string
    private const string InterceptorBoilerplate = """
        using CoreOne;
        using CoreOne.Attributes;
        using System.Threading.Tasks;

        public class MyInterceptor : IAsyncInterceptor
        {
            public Task<object?> InterceptAsync(IInvocation invocation) => invocation.ProceedAsync();
        }

        """;

    private static Compilation CreateCompilation(string source)
    {
        var loadedAssemblies = AppDomain.CurrentDomain.GetAssemblies()
            .Where(a => !a.IsDynamic && !string.IsNullOrEmpty(a.Location))
            .Select(a => MetadataReference.CreateFromFile(a.Location))
            .Cast<MetadataReference>();

        // Ensure the CoreOne assembly is in the references (needed for InterceptedByAttribute, IAsyncInterceptor etc.)
        var coreOneRef = MetadataReference.CreateFromFile(typeof(InterceptedByAttribute).Assembly.Location);

        var references = loadedAssemblies.Append(coreOneRef).ToArray();

        return CSharpCompilation.Create(
            "TestAssembly",
            [CSharpSyntaxTree.ParseText(source)],
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
    }

    private static ImmutableArray<GeneratedSourceResult> RunGenerator(string source)
    {
        var compilation = CreateCompilation(source);
        var generator = new ProxyGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        driver = (CSharpGeneratorDriver)driver.RunGenerators(compilation);
        return driver.GetRunResult().Results[0].GeneratedSources;
    }

    // ── No-output cases ─────────────────────────────────────────────────────────

    [Test]
    public void Generator_ClassWithoutAttribute_ProducesNoOutput()
    {
        const string source = """
            public class MyService
            {
                public virtual void Execute() { }
            }
            """;

        var sources = RunGenerator(source);
        Assert.That(sources, Is.Empty);
    }

    [Test]
    public void Generator_ClassWithAttributeButNoInterceptorType_ProducesNoOutput()
    {
        // InterceptedByAttribute requires at least one constructor argument; this tests
        // the GetInterceptorTypes guard that returns early when the list is empty.
        // We simulate this by using only a class that the generator will not recognize.
        const string source = InterceptorBoilerplate + """
            public class PlainService
            {
                public virtual void Execute() { }
            }
            """;

        var sources = RunGenerator(source);
        Assert.That(sources, Is.Empty);
    }

    // ── Basic proxy shape ────────────────────────────────────────────────────────

    [Test]
    public void Generator_ClassWithAttribute_GeneratesProxyFileWithCorrectHintName()
    {
        var source = InterceptorBoilerplate + """
            [InterceptedBy(typeof(MyInterceptor))]
            public class MyService
            {
                public virtual void Execute() { }
            }
            """;

        var sources = RunGenerator(source);
        Assert.That(sources, Has.Length.EqualTo(1));
        Assert.That(sources[0].HintName, Is.EqualTo("MyServiceProxy.g.cs"));
    }

    [Test]
    public void Generator_ClassWithAttribute_GeneratesAutoGeneratedHeader()
    {
        var source = InterceptorBoilerplate + """
            [InterceptedBy(typeof(MyInterceptor))]
            public class MyService
            {
                public virtual void Execute() { }
            }
            """;

        var generated = RunGenerator(source)[0].SourceText.ToString();
        using (Assert.EnterMultipleScope())
        {
            Assert.That(generated, Does.Contain("// <auto-generated/>"));
            Assert.That(generated, Does.Contain("#nullable enable"));
            Assert.That(generated, Does.Contain("using System.Reflection;"));
            Assert.That(generated, Does.Contain("using System.Threading.Tasks;"));
        }
    }

    [Test]
    public void Generator_ClassWithAttribute_GeneratesPartialProxyInheritingFromOriginal()
    {
        var source = InterceptorBoilerplate + """
            [InterceptedBy(typeof(MyInterceptor))]
            public class MyService
            {
                public virtual void Execute() { }
            }
            """;

        var generated = RunGenerator(source)[0].SourceText.ToString();
        Assert.That(generated, Does.Contain("public partial class MyServiceProxy : MyService"));
    }

    [Test]
    public void Generator_ClassWithAttribute_GeneratesInterceptorArrayFieldAndConstructor()
    {
        var source = InterceptorBoilerplate + """
            [InterceptedBy(typeof(MyInterceptor))]
            public class MyService
            {
                public virtual void Execute() { }
            }
            """;

        var generated = RunGenerator(source)[0].SourceText.ToString();
        using (Assert.EnterMultipleScope())
        {
            Assert.That(generated, Does.Contain("private readonly IAsyncInterceptor[] _interceptors;"));
            Assert.That(generated, Does.Contain("public MyServiceProxy(MyInterceptor interceptor0)"));
            Assert.That(generated, Does.Contain("_interceptors = new IAsyncInterceptor[] { interceptor0 }"));
        }
    }

    // ── Non-virtual methods are skipped ─────────────────────────────────────────

    [Test]
    public void Generator_ClassWithAttributeButNoVirtualMethods_GeneratesProxyWithNoOverrides()
    {
        var source = InterceptorBoilerplate + """
            [InterceptedBy(typeof(MyInterceptor))]
            public class MyService
            {
                public string GetName() => "test";
            }
            """;

        var generated = RunGenerator(source)[0].SourceText.ToString();
        Assert.That(generated, Does.Not.Contain("public override"));
    }

    // ── Method override variants ─────────────────────────────────────────────────

    [Test]
    public void Generator_WithVoidVirtualMethod_GeneratesOverrideWithSyncChaining()
    {
        var source = InterceptorBoilerplate + """
            [InterceptedBy(typeof(MyInterceptor))]
            public class MyService
            {
                public virtual void Execute() { }
            }
            """;

        var generated = RunGenerator(source)[0].SourceText.ToString();
        using (Assert.EnterMultipleScope())
        {
            Assert.That(generated, Does.Contain("public override void Execute()"));
            Assert.That(generated, Does.Contain("base.Execute();"));
            // void ProceedAsync returns null
            Assert.That(generated, Does.Contain("return null;"));
            // sync chaining via GetAwaiter().GetResult()
            Assert.That(generated, Does.Contain(".GetAwaiter().GetResult()"));
            // void methods must NOT emit a return-cast statement
            Assert.That(generated, Does.Not.Contain("return (void)result"));
        }
    }

    [Test]
    public void Generator_WithSyncReturnVirtualMethod_GeneratesOverrideWithCastReturn()
    {
        var source = InterceptorBoilerplate + """
            [InterceptedBy(typeof(MyInterceptor))]
            public class MyService
            {
                public virtual int Calculate(int x, int y) => x + y;
            }
            """;

        var generated = RunGenerator(source)[0].SourceText.ToString();
        using (Assert.EnterMultipleScope())
        {
            Assert.That(generated, Does.Contain("public override int Calculate(int x, int y)"));
            Assert.That(generated, Does.Contain("return base.Calculate(x, y)"));
            Assert.That(generated, Does.Contain(".GetAwaiter().GetResult()"));
            Assert.That(generated, Does.Contain("return (int)result!;"));
        }
    }

    [Test]
    public void Generator_WithAsyncTaskVirtualMethod_GeneratesAsyncOverrideWithoutReturn()
    {
        var source = InterceptorBoilerplate + """
            [InterceptedBy(typeof(MyInterceptor))]
            public class MyService
            {
                public virtual async System.Threading.Tasks.Task ExecuteAsync()
                {
                    await System.Threading.Tasks.Task.CompletedTask;
                }
            }
            """;

        var generated = RunGenerator(source)[0].SourceText.ToString();
        using (Assert.EnterMultipleScope())
        {
            Assert.That(generated, Does.Contain("public override async System.Threading.Tasks.Task ExecuteAsync()"));
            // ProceedAsync awaits the base call and returns null for non-generic Task
            Assert.That(generated, Does.Contain("await base.ExecuteAsync();"));
            Assert.That(generated, Does.Contain("return null;"));
            // async chaining via await (not .GetAwaiter().GetResult())
            Assert.That(generated, Does.Contain("var result = await next(invocation);"));
            Assert.That(generated, Does.Not.Contain(".GetAwaiter().GetResult()"));
            // no cast-return for plain Task
            Assert.That(generated, Does.Not.Contain("return (System.Threading.Tasks.Task)result"));
        }
    }

    [Test]
    public void Generator_WithAsyncTaskTVirtualMethod_GeneratesAsyncOverrideWithCastReturn()
    {
        var source = InterceptorBoilerplate + """
            [InterceptedBy(typeof(MyInterceptor))]
            public class MyService
            {
                public virtual System.Threading.Tasks.Task<string> GetNameAsync()
                    => System.Threading.Tasks.Task.FromResult("hello");
            }
            """;

        var generated = RunGenerator(source)[0].SourceText.ToString();
        using (Assert.EnterMultipleScope())
        {
            Assert.That(generated, Does.Contain("public override async System.Threading.Tasks.Task<string> GetNameAsync()"));
            Assert.That(generated, Does.Contain("return await base.GetNameAsync();"));
            Assert.That(generated, Does.Contain("var result = await next(invocation);"));
            Assert.That(generated, Does.Contain("return (string)result!;"));
        }
    }

    // ── Method parameter capture ─────────────────────────────────────────────────

    [Test]
    public void Generator_WithMethodParameters_CapturesArgumentsInInvocation()
    {
        var source = InterceptorBoilerplate + """
            [InterceptedBy(typeof(MyInterceptor))]
            public class MyService
            {
                public virtual string Process(string name, int count) => name;
            }
            """;

        var generated = RunGenerator(source)[0].SourceText.ToString();
        using (Assert.EnterMultipleScope())
        {
            Assert.That(generated, Does.Contain("Arguments = new object[] { name, count }"));
            Assert.That(generated, Does.Contain("base.Process(name, count)"));
        }
    }

    // ── Static MethodInfo caching ────────────────────────────────────────────────

    [Test]
    public void Generator_GeneratesStaticMethodInfoCaching()
    {
        var source = InterceptorBoilerplate + """
            [InterceptedBy(typeof(MyInterceptor))]
            public class MyService
            {
                public virtual void Execute() { }
            }
            """;

        // Safe method name for Execute() with no params is "Execute_"
        var generated = RunGenerator(source)[0].SourceText.ToString();
        using (Assert.EnterMultipleScope())
        {
            Assert.That(generated, Does.Contain("private static readonly MethodInfo _Execute_Method"));
            Assert.That(generated, Does.Contain("private static MethodInfo GetMethodInfo_Execute_()"));
            Assert.That(generated, Does.Contain("typeof(MyService).GetMethod(\"Execute\""));
            Assert.That(generated, Does.Contain("BindingFlags.Public | BindingFlags.Instance"));
            // Method field is referenced inside the invocation
            Assert.That(generated, Does.Contain("Method = _Execute_Method,"));
        }
    }

    [Test]
    public void Generator_SafeMethodName_IncludesParameterTypeNames()
    {
        var source = InterceptorBoilerplate + """
            [InterceptedBy(typeof(MyInterceptor))]
            public class MyService
            {
                public virtual int Add(int x, int y) => x + y;
            }
            """;

        // Safe method name: "Add_Int32_Int32"
        var generated = RunGenerator(source)[0].SourceText.ToString();
        using (Assert.EnterMultipleScope())
        {
            Assert.That(generated, Does.Contain("_Add_Int32_Int32Method"));
            Assert.That(generated, Does.Contain("GetMethodInfo_Add_Int32_Int32()"));
        }
    }

    // ── Interceptor chaining ─────────────────────────────────────────────────────

    [Test]
    public void Generator_GeneratesInterceptorChainLoop()
    {
        var source = InterceptorBoilerplate + """
            [InterceptedBy(typeof(MyInterceptor))]
            public class MyService
            {
                public virtual void Execute() { }
            }
            """;

        var generated = RunGenerator(source)[0].SourceText.ToString();
        using (Assert.EnterMultipleScope())
        {
            Assert.That(generated, Does.Contain("Func<IInvocation, Task<object?>> next = (inv) => inv.ProceedAsync();"));
            Assert.That(generated, Does.Contain("for (int i = _interceptors.Length - 1; i >= 0; i--)"));
            Assert.That(generated, Does.Contain("var interceptor = _interceptors[i];"));
            Assert.That(generated, Does.Contain("var currentNext = next;"));
            Assert.That(generated, Does.Contain("next = (inv) => interceptor.InterceptAsync(new Invocation"));
            Assert.That(generated, Does.Contain("ProceedAsync = () => currentNext(inv)"));
        }
    }

    // ── Multiple interceptors ────────────────────────────────────────────────────

    [Test]
    public void Generator_WithMultipleInterceptors_GeneratesMultipleConstructorParameters()
    {
        var source = """
            using CoreOne;
            using CoreOne.Attributes;
            using System.Threading.Tasks;

            public class InterceptorA : IAsyncInterceptor
            {
                public Task<object?> InterceptAsync(IInvocation invocation) => invocation.ProceedAsync();
            }

            public class InterceptorB : IAsyncInterceptor
            {
                public Task<object?> InterceptAsync(IInvocation invocation) => invocation.ProceedAsync();
            }

            [InterceptedBy(typeof(InterceptorA))]
            [InterceptedBy(typeof(InterceptorB))]
            public class MyService
            {
                public virtual void Execute() { }
            }
            """;

        var sources = RunGenerator(source);
        Assert.That(sources, Has.Length.EqualTo(1));
        var generated = sources[0].SourceText.ToString();
        using (Assert.EnterMultipleScope())
        {
            Assert.That(generated, Does.Contain("InterceptorA interceptor0"));
            Assert.That(generated, Does.Contain("InterceptorB interceptor1"));
            Assert.That(generated, Does.Contain("interceptor0, interceptor1"));
        }
    }

    // ── Namespace handling ───────────────────────────────────────────────────────

    [Test]
    public void Generator_ClassInNamespace_GeneratesProxyInSameNamespace()
    {
        const string source = """
            using CoreOne;
            using CoreOne.Attributes;
            using System.Threading.Tasks;

            namespace MyApp.Services
            {
                public class MyInterceptor : IAsyncInterceptor
                {
                    public Task<object?> InterceptAsync(IInvocation invocation) => invocation.ProceedAsync();
                }

                [InterceptedBy(typeof(MyInterceptor))]
                public class MyService
                {
                    public virtual void Execute() { }
                }
            }
            """;

        var generated = RunGenerator(source)[0].SourceText.ToString();
        Assert.That(generated, Does.Contain("namespace MyApp.Services"));
    }

    [Test]
    public void Generator_ClassInGlobalNamespace_GeneratesProxyWithoutNamespaceBlock()
    {
        var source = InterceptorBoilerplate + """
            [InterceptedBy(typeof(MyInterceptor))]
            public class MyService
            {
                public virtual void Execute() { }
            }
            """;

        var generated = RunGenerator(source)[0].SourceText.ToString();
        Assert.That(generated, Does.Not.Contain("namespace "));
    }

    // ── Generic methods ──────────────────────────────────────────────────────────

    [Test]
    public void Generator_WithGenericVirtualMethod_GeneratesGenericOverrideWithMethodInfoLoop()
    {
        var source = InterceptorBoilerplate + """
            [InterceptedBy(typeof(MyInterceptor))]
            public class MyService
            {
                public virtual T Get<T>(T value) => value;
            }
            """;

        var generated = RunGenerator(source)[0].SourceText.ToString();
        using (Assert.EnterMultipleScope())
        {
            Assert.That(generated, Does.Contain("public override T Get<T>(T value)"));
            Assert.That(generated, Does.Contain("base.Get<T>(value)"));
            // Generic methods use a loop to find the MethodInfo
            Assert.That(generated, Does.Contain("foreach (var m in typeof(MyService).GetMethods("));
            Assert.That(generated, Does.Contain("m.IsGenericMethod"));
        }
    }

    // ── Multiple classes ─────────────────────────────────────────────────────────

    [Test]
    public void Generator_MultipleClasses_OnlyProcessesAttributedClasses()
    {
        var source = InterceptorBoilerplate + """
            [InterceptedBy(typeof(MyInterceptor))]
            public class ServiceA
            {
                public virtual void Execute() { }
            }

            public class ServiceB
            {
                public virtual void Execute() { }
            }
            """;

        var sources = RunGenerator(source);
        Assert.That(sources, Has.Length.EqualTo(1));
        Assert.That(sources[0].HintName, Is.EqualTo("ServiceAProxy.g.cs"));
    }

    [Test]
    public void Generator_TwoAttributedClasses_GeneratesTwoProxyFiles()
    {
        var source = InterceptorBoilerplate + """
            [InterceptedBy(typeof(MyInterceptor))]
            public class ServiceA
            {
                public virtual void Execute() { }
            }

            [InterceptedBy(typeof(MyInterceptor))]
            public class ServiceB
            {
                public virtual void Run() { }
            }
            """;

        var sources = RunGenerator(source);
        Assert.That(sources, Has.Length.EqualTo(2));
        var hints = sources.Select(s => s.HintName).ToArray();
        Assert.That(hints, Does.Contain("ServiceAProxy.g.cs"));
        Assert.That(hints, Does.Contain("ServiceBProxy.g.cs"));
    }

    // ── Override methods (not just virtual) ─────────────────────────────────────

    [Test]
    public void Generator_ClassWithOverrideMethod_AlsoGeneratesProxyOverride()
    {
        var source = InterceptorBoilerplate + """
            public class BaseService
            {
                public virtual void Execute() { }
            }

            [InterceptedBy(typeof(MyInterceptor))]
            public class DerivedService : BaseService
            {
                public override void Execute() { }
            }
            """;

        var sources = RunGenerator(source);
        Assert.That(sources, Has.Length.EqualTo(1));
        var generated = sources[0].SourceText.ToString();
        using (Assert.EnterMultipleScope())
        {
            Assert.That(sources[0].HintName, Is.EqualTo("DerivedServiceProxy.g.cs"));
            Assert.That(generated, Does.Contain("public partial class DerivedServiceProxy : DerivedService"));
            Assert.That(generated, Does.Contain("public override void Execute()"));
        }
    }

    // ── MethodName captured in Invocation ───────────────────────────────────────

    [Test]
    public void Generator_Invocation_ContainsMethodNameString()
    {
        var source = InterceptorBoilerplate + """
            [InterceptedBy(typeof(MyInterceptor))]
            public class MyService
            {
                public virtual void Execute() { }
            }
            """;

        var generated = RunGenerator(source)[0].SourceText.ToString();
        Assert.That(generated, Does.Contain("MethodName = \"Execute\","));
    }

    // ── Generic attribute form (C# 11+) ─────────────────────────────────────────

    [Test]
    public void Generator_WithGenericAttributeForm_GeneratesProxy()
    {
        // InterceptedByAttribute<T> is itself an attribute (generic attribute, C# 11+).
        // The syntax predicate checks baseFullName == "CoreOne.Attributes.InterceptedByAttribute"
        // which matches for InterceptedByAttribute<T> whose base IS InterceptedByAttribute.
        const string source = """
            using CoreOne;
            using CoreOne.Attributes;
            using System.Threading.Tasks;

            public class MyInterceptor : IAsyncInterceptor
            {
                public Task<object?> InterceptAsync(IInvocation invocation) => invocation.ProceedAsync();
            }

            [InterceptedBy<MyInterceptor>]
            public class MyService
            {
                public virtual void Execute() { }
            }
            """;

        var compilation = CreateCompilation(source);
        var generator = new ProxyGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        driver = (CSharpGeneratorDriver)driver.RunGenerators(compilation);
        var sources = driver.GetRunResult().Results[0].GeneratedSources;

        Assert.That(sources, Has.Length.EqualTo(1));
        var generated = sources[0].SourceText.ToString();
        using (Assert.EnterMultipleScope())
        {
            Assert.That(sources[0].HintName, Is.EqualTo("MyServiceProxy.g.cs"));
            Assert.That(generated, Does.Contain("public partial class MyServiceProxy : MyService"));
            Assert.That(generated, Does.Contain("MyInterceptor interceptor0"));
        }
    }
}
